# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Editado em')),
                ('name', models.CharField(max_length=75, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setor',
            },
        ),
    ]
