# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 00:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Editado em')),
                ('patrimony', models.CharField(max_length=75, unique=True, verbose_name='Número de patrimônio')),
                ('serial_number', models.CharField(max_length=75, unique=True, verbose_name='Número de série')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
            },
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Editado em'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.EquipmentType', verbose_name='Tipo de equipamento'),
        ),
    ]
