# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0001_initial'),
        ('equipments', '0002_auto_20171102_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sectors.Sector', verbose_name='Setor'),
        ),
    ]
