# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 02:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0004_auto_20171102_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='equipments.EquipmentType', verbose_name='Tipo de equipamento'),
        ),
    ]
