# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0001_initial'),
        ('equipments', '0005_auto_20171102_0202'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Editado em')),
                ('checkin', models.DateTimeField(auto_now_add=True, verbose_name='Dia/Hora - Chegada')),
                ('checkout', models.DateTimeField(blank=True, null=True, verbose_name='Dia/Hora - Saída')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='equipments.Equipment', verbose_name='Equipamento')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sectors.Sector', verbose_name='Setor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
