# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0006_equipmenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='function',
            field=models.CharField(choices=[('loan', 'Empréstimo'), ('transport', 'Transporte')], default='loan', max_length=9, verbose_name='Função'),
        ),
    ]
