# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0007_equipment_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='equipment_model',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Fabricante'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='year_of_manufacture',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Ano de fabricação'),
        ),
    ]
