# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0008_auto_20171124_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_model',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='Modelo'),
        ),
    ]
