# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0009_auto_20171124_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenthistory',
            name='order_of_service',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='Ordem de Serviço'),
        ),
    ]
