# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0010_equipmenthistory_order_of_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmenthistory',
            name='order_of_service',
        ),
        migrations.AddField(
            model_name='equipment',
            name='order_of_service',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='Ordem de Serviço'),
        ),
    ]
